name: Build Kivy APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build APK with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: .
        buildozer_version: main
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: bin/*.apk
        retention-days: 30
