name: Build Kivy APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          git \
          wget \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          ninja-build \
          libffi-dev \
          libssl-dev
        
    - name: Install Buildozer and requirements
      run: |
        python3 -m pip install --upgrade pip
        pip3 install buildozer cython pillow virtualenv
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
        
    - name: Setup Android SDK
      run: |
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses || true
        
    - name: Initialize Buildozer
      run: |
        buildozer init || true
        ls -la
        cat buildozer.spec || echo "No buildozer.spec found"
        
    - name: Build APK
      run: |
        buildozer android clean
        buildozer -v android debug
        ls -la bin/ || echo "No bin directory"
        
    - name: Upload APK
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: bin/*.apk
        retention-days: 30
        
    - name: Show build logs on failure
      if: failure()
      run: |
        echo "=== Build failed ==="
        find . -name "*.log" -exec echo "=== {} ===" \; -exec cat {} \; || true
